### ISSUE TITLE
#51 百度云样式重置

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/esay-bug-library#53]
``` css
html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td {
    padding: 0;
    margin: 0;
    border: 0;
    outline: 0;
    font-weight: inherit;
    font-style: inherit;
    font-family: inherit;
    font-size: 100%;
    vertical-align: baseline;
}

body {
    font-size: 12px;
    line-height: 1.5em;
    color: #333;
    background-color: #E8ECF0;
    min-width: 1280px;
    font-family: -apple-system,BlinkMacSystemFont,"SF Pro SC","SF Pro Text","Helvetica Neue",Helvetica,"PingFang SC","Segoe UI",Roboto,"Hiragino Sans GB","Arial","microsoft yahei ui","Microsoft YaHei",SimSun,sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```

**Comment by Easy-MJ** [comment]
``` css
.icon-spin.iconfont {
	display: inline-block;
	-webkit-animation: icon-spin 2s infinite linear;
	animation: icon-spin 2s infinite linear
}

.icon-pulse.iconfont {
	display: inline-block;
	-webkit-animation: icon-spin 1s infinite steps(8);
	animation: icon-spin 1s infinite steps(8)
}

.icon-rotate-90 {
	display: inline-block;
	-webkit-transform: rotate(90deg);
	transform: rotate(90deg);
	-ms-filter: "progid:DXImageTransform.Microsoft.BasicImage(rotation=1)";
	-ms-transform: rotate(90deg)
}

.icon-rotate-180 {
	display: inline-block;
	-webkit-transform: rotate(180deg);
	transform: rotate(180deg);
	-ms-filter: "progid:DXImageTransform.Microsoft.BasicImage(rotation=2)";
	-ms-transform: rotate(180deg)
}

.icon-rotate-270 {
	display: inline-block;
	-webkit-transform: rotate(270deg);
	transform: rotate(270deg);
	-ms-filter: "progid:DXImageTransform.Microsoft.BasicImage(rotation=3)";
	-ms-transform: rotate(270deg)
}

.icon-flip-horizontal {
	display: inline-block;
	-webkit-transform: scale(-1,1);
	transform: scale(-1,1);
	-ms-filter: "progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1)";
	-ms-transform: scale(-1,1)
}

.icon-flip-vertical {
	display: inline-block;
	-webkit-transform: scale(1,-1);
	transform: scale(1,-1);
	-ms-filter: "progid:DXImageTransform.Microsoft.BasicImage(rotation=2, mirror=1)";
	-ms-transform: scale(1,-1)
}

@-webkit-keyframes icon-spin {
	0% {
		-webkit-transform: rotate(0);
		transform: rotate(0)
	}

	100% {
		-webkit-transform: rotate(359deg);
		transform: rotate(359deg)
	}
}

@keyframes icon-spin {
	0% {
		-webkit-transform: rotate(0);
		transform: rotate(0)
	}

	100% {
		-webkit-transform: rotate(359deg);
		transform: rotate(359deg)
	}
}

.layout {
	display: -webkit-box;
	display: -ms-flexbox;
	display: flex
}
[tip] {
	position: relative
}
[tip]:after {
	position: absolute;
	top: 50%;
	left: 100%;
	z-index: 1;
	display: block;
	visibility: hidden;
	padding: 0 4px;
	width: auto;
	background-color: rgba(18,26,44,.8);
	box-shadow: 0 0 14px rgba(0,0,0,.1);
	color: #fff;
	content: attr(tip);
	white-space: pre;
	font-size: 12px;
	line-height: 18px;
	opacity: 0;
	-webkit-transition: all .3s;
	transition: all .3s;
	-webkit-transform: translate(-5px,-50%);
	transform: translate(-5px,-50%);
	pointer-events: none
}
[tip]:hover {
	overflow: visible
}
[tip]:hover:after {
	display: block;
	visibility: visible;
	opacity: .8;
	-webkit-transform: translate(5px,-50%);
	transform: translate(5px,-50%)
}
[tip].tip-top:after,[tip][tip-align=top]:after {
	top: auto;
	bottom: 100%;
	left: 50%;
	-webkit-transform: translate(-50%,5px);
	transform: translate(-50%,5px)
}
[tip].tip-top:hover:after,[tip][tip-align=top]:hover:after {
	-webkit-transform: translate(-50%,-5px);
	transform: translate(-50%,-5px)
}
[tip].tip-bottom:after,[tip][tip-align=bottom]:after {
	top: 100%;
	bottom: auto;
	left: 50%;
	-webkit-transform: translate(-50%,-5px);
	transform: translate(-50%,-5px)
}
[tip].tip-bottom:hover:after,[tip][tip-align=bottom]:hover:after {
	-webkit-transform: translate(-50%,5px);
	transform: translate(-50%,5px)
}
[tip].tip-left:after,[tip][tip-align=left]:after {
	top: 50%;
	right: 100%;
	bottom: auto;
	left: auto;
	-webkit-transform: translate(5px,-50%);
	transform: translate(5px,-50%)
}
[tip].tip-left:hover:after,[tip][tip-align=left]:hover:after {
	-webkit-transform: translate(-5px,-50%);
	transform: translate(-5px,-50%)
}
[tip].tip-disable:after {
	visibility: hidden!important
}
[tip=""]:after {
	visibility: hidden!important
}

@-webkit-keyframes fadeIn {
	0% {
		opacity: 0;
		-webkit-transform: scale(.8);
		transform: scale(.8)
	}

	100% {
		opacity: 1;
		-webkit-transform: scale(1);
		transform: scale(1)
	}
}

@keyframes fadeIn {
	0% {
		opacity: 0;
		-webkit-transform: scale(.8);
		transform: scale(.8)
	}

	100% {
		opacity: 1;
		-webkit-transform: scale(1);
		transform: scale(1)
	}
}

@-webkit-keyframes fadeOut {
	0% {
		opacity: 1;
		-webkit-transform: scale(1);
		transform: scale(1)
	}

	100% {
		opacity: 0;
		-webkit-transform: scale(.8);
		transform: scale(.8)
	}
}

@keyframes fadeOut {
	0% {
		opacity: 1;
		-webkit-transform: scale(1);
		transform: scale(1)
	}

	100% {
		opacity: 0;
		-webkit-transform: scale(.8);
		transform: scale(.8)
	}
}

.ui-radioselect {
	display: inline-block;
	overflow: hidden;
	border: 1px solid #6481CD;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	border-radius: 5px;
	vertical-align: middle;
	zoom: 1
}

.ui-radioselect:after,.ui-radioselect:before {
	display: table;
	content: ""
}

.ui-radioselect:after {
	clear: both
}

.ui-radioselect:after,.ui-radioselect:before {
	display: table;
	content: ""
}

.ui-radioselect:after {
	clear: both
}

.ui-radioselect:after,.ui-radioselect:before {
	display: table;
	content: ""
}

.ui-radioselect:after {
	clear: both
}

.ui-radioselect:after,.ui-radioselect:before {
	display: table;
	content: ""
}

.ui-radioselect:after {
	clear: both
}

.ui-radio-block {
	float: left;
	padding: 0 10px;
	height: 28px;
	min-width: 58px;
	border-right: 1px solid #6481CD;
	background-color: #F1F5FD;
	color: #6481CD;
	text-align: center;
	font-size: 12px;
	line-height: 28px;
	cursor: pointer
}

.ui-radio-block:last-child {
	border-right: none
}

.ui-radio-block:hover .ui-radio-item-hover {
	display: block
}

.ui-radio-block:hover .arrow-down {
	display: block
}

.ui-radio-disabled {
	background-color: #F1F5FD;
	color: #D0DAF3;
	cursor: not-allowed
}

.ui-radio-selected {
	background-color: #6481CD;
	color: #FFF;
	cursor: default
}

.ui-radio-item-hover {
	position: absolute;
	top: -44px;
	left: -65px;
	display: none;
	padding-right: 10px;
	padding-left: 10px;
	height: 25px;
	min-width: 150px;
	border: 1px solid #CCC;
	-webkit-border-radius: 3px;
	-moz-border-radius: 3px;
	border-radius: 3px;
	background: #FFF;
	-webkit-box-shadow: 1px 1px 8px rgba(0,0,0,.2);
	-moz-box-shadow: 1px 1px 8px rgba(0,0,0,.2);
	box-shadow: 1px 1px 8px rgba(0,0,0,.2);
	color: #333;
	line-height: 25px
}

.arrow-down {
	position: absolute;
	top: -17px;
	left: 14px;
	display: none;
	width: 0;
	height: 0;
	border-color: #CCC transparent transparent transparent;
	border-style: solid dashed dashed dashed;
	border-width: 10px
}

.arrow-down i {
	position: absolute;
	top: -11px;
	left: -10px;
	display: block;
	width: 0;
	height: 0;
	border-color: #fff transparent transparent transparent;
	border-style: solid dashed dashed dashed;
	border-width: 10px
}

.ui-radioselect-disabled .ui-radio-block {
	background-color: #F1F5FD;
	color: #D0DAF3;
	cursor: not-allowed
}

.ui-radioselect-disabled .ui-radio-selected {
	background-color: #6481CD;
	color: #FFF
}

.ui-dragger {
	position: relative
}

.ui-dragger .ui-dragger-bar {
	position: relative;
	background: #ccc;
	cursor: pointer
}

.ui-dragger .ui-dragger-bar-middle {
	position: absolute;
	height: 20px;
	color: #999;
	text-align: center;
	font-size: 12px;
	line-height: 20px
}

.ui-dragger .ui-dragger-bar-vertical {
	bottom: 16px;
	left: 0;
	width: 20px
}

.ui-dragger .ui-dragger-bar-selected {
	position: absolute;
	background: #477adf
}

.ui-dragger .ui-dragger-bar-selected-horizontal {
	top: 50%;
	margin-top: -5px;
	width: 0;
	height: 10px;
	font-size: 8px
}

.ui-dragger .ui-dragger-bar-selected-vertical {
	bottom: 0;
	left: 50%;
	margin-left: -5px;
	width: 10px;
	height: 0;
	font-size: 0
}

.ui-dragger .ui-dragger-bar-left {
	position: absolute;
	top: 0;
	left: -30px;
	padding-left: 0;
	width: 30px;
	height: 6px;
	color: #999;
	font-size: 12px
}

.ui-dragger .ui-dragger-bar-right {
	position: absolute;
	top: 0;
	right: -29px;
	padding-right: 0;
	width: 30px;
	height: 20px;
	color: #999;
	font-size: 12px
}

.ui-dragger .ui-dragger-bar-bottom {
	position: absolute;
	bottom: -15px;
	left: 0;
	width: 20px;
	height: 15px;
	font-size: 12px
}

.ui-dragger .ui-dragger-bar-top {
	position: absolute;
	top: -15px;
	left: 0;
	width: 20px;
	height: 15px;
	font-size: 12px
}

.ui-dragger .ui-dragger-control-bar {
	position: absolute;
	z-index: 1;
	border-radius: 10px;
	color: #777;
	text-align: center;
	font-weight: 700;
	cursor: pointer
}

.ui-dragger .ui-dragger-control-bar-horizontal {
	top: -6px
}

.ui-dragger .ui-dragger-control-bar-vertical {
	left: -21px
}

.ui-dragger .ui-dragger-control-panel {
	position: absolute;
	left: 0
}

.ui-dragger .ui-dragger-control-panel-horizontal {
	top: 50px
}

.ui-dragger .ui-dragger-ruling {
	position: absolute
}

.ui-dragger .ui-dragger-ruling li {
	position: absolute;
	background: #d8d8d8;
	box-shadow: 0 0 1px #ccc;
	cursor: pointer
}

.ui-dragger .ui-dragger-ruling-num {
	position: absolute
}

.ui-dragger .ui-dragger-ruling-num li {
	position: absolute;
	color: #999;
	text-align: center;
	text-shadow: 0 0 3px #ccc;
	font-size: 20px
}

.ui-dragger .ui-dragger-ruling-num-horizontal {
	top: -37px
}

.ui-dragger .ui-dragger-ruling-num-vertical {
	right: -38px
}

.ui-dragger .ui-dragger-ruling-horizontal {
	top: -15px;
	left: 0
}

.ui-dragger .ui-dragger-ruling-horizontal li {
	width: 1px;
	height: 10px
}

.ui-dragger .ui-dragger-ruling-vertical {
	right: -8px;
	bottom: 0
}

.ui-dragger .ui-dragger-ruling-vertical li {
	width: 25px;
	height: 1px
}

.ui-dragger-icon {
	position: absolute;
	top: -4px;
	left: 660px;
	width: 27px;
	height: 27px;
	cursor: pointer
}

.ui-dragger-icon-plus {
	background: url(../../dep/inf-ria/0.0.0/ui/img/plus_icon.png) no-repeat
}

.ui-dragger-icon-delete {
	background: url(../../dep/inf-ria/0.0.0/ui/img/delete_icon.png) no-repeat
}

.ui-dragger {
	height: 30px
}

.ui-dragger .ui-dragger-bar.ui-dragger-bar-horizontal {
	top: 6px;
	left: 8px;
	height: 6px;
	border: none;
	background: #e3e8f7
}

.ui-dragger .ui-dragger-bar .ui-dragger-bar-left {
	left: -8px;
	width: 17px;
	height: 6px;
	-webkit-border-bottom-left-radius: 3px;
	-moz-border-radius-bottomleft: 3px;
	border-bottom-left-radius: 3px;
	-webkit-border-top-left-radius: 3px;
	-moz-border-radius-topleft: 3px;
	border-top-left-radius: 3px;
	background: #6583cc;
	line-height: 38px
}

.ui-dragger .ui-dragger-bar .ui-dragger-bar-middle {
	line-height: 38px
}

.ui-dragger .ui-dragger-bar .ui-dragger-bar-right {
	top: 0;
	right: -8px;
	width: 17px;
	height: 6px;
	border: none;
	-webkit-border-top-right-radius: 3px;
	-moz-border-radius-topright: 3px;
	border-top-right-radius: 3px;
	-webkit-border-bottom-right-radius: 3px;
	-moz-border-radius-bottomright: 3px;
	border-bottom-right-radius: 3px;
	background: #e3e8f7;
	line-height: 38px
}

.ui-dragger .ui-dragger-bar .ui-dragger-bar-right .ui-dragger-bar-right-text {
	position: absolute;
	right: 0
}

.ui-dragger .ui-dragger-bar .ui-dragger-bar-selected.ui-dragger-bar-selected-horizontal {
	top: 0;
	margin-top: 0;
	height: 100%;
	border: none;
	background: #6583cc
}

.ui-dragger .ui-dragger-bar-tip {
	position: relative;
	top: -35px;
	display: inline-block;
	display: none;
	padding: 0 5px;
	height: 18px;
	min-width: 40px;
	border: 1px solid #b0c0e7;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	border-radius: 5px;
	text-align: center;
	font-size: 12px;
	line-height: 18px
}

.ui-dragger .ui-dragger-bar-tip:after {
	position: relative;
	left: 15px;
	display: block;
	width: 0;
	height: 0;
	border-top: 5px solid #b0c0e7;
	border-right: 6px solid transparent;
	border-left: 6px solid transparent;
	content: ''
}

.ui-dragger .ui-dragger-control-bar.ui-dragger-control-bar-horizontal {
	top: 0;
	width: 17px;
	height: 20px;
	border-radius: 0;
	background: url(../../dep/inf-ria/0.0.0/ui/img/dragger/draggerBtn.png) no-repeat
}

.ui-dragger .ui-dragger-control-bar.ui-dragger-control-bar-horizontal:hover {
	background: url(../../dep/inf-ria/0.0.0/ui/img/dragger/draggerBtnHover.png) no-repeat
}

.ui-dragger .ui-dragger-control-bar.ui-dragger-control-bar-horizontal:active {
	background: url(../../dep/inf-ria/0.0.0/ui/img/dragger/draggerBtnActive.png) no-repeat
}

.ui-dragger .ui-textbox {
	left: 385px
}

.ui-dragger input {
	position: relative;
	top: -10px;
	left: 0;
	padding: 0;
	padding-left: 10px;
	width: 78px;
	height: 26px;
	border: 1px solid #b0c0e7;
	-webkit-border-radius: 3px;
	-moz-border-radius: 3px;
	border-radius: 3px;
	background: 0 0;
	color: #333;
	text-align: left
}

.ui-dragger input:hover {
	border: 1px solid #b0c0e7
}

.ui-dragger .ui-dragger-icon {
	top: 0;
	left: 492px
}

.ui-dragger .ui-dragger-icon.ui-dragger-icon-delete {
	top: -3px;
	left: 470px
}

.ui-smscodebox .ui-button {
	position: relative;
	display: inline-block;
	margin-left: 10px
}

.ui-smscodebox .ui-button-disabled,.ui-smscodebox .ui-button-disabled:active,.ui-smscodebox .ui-button-disabled:hover {
	background: 0 0
}

.ui-smscodebox-validity-label {
	font-size: 12px
}

.ui-smscodebox-validity-label-invalid {
	color: #EB5252
}

.ui-numbertextline .ui-button {
	padding: 0;
	width: 28px;
	height: 28px;
	outline: 0;
	background: #FFF;
	color: #6583CC;
	font-weight: 700;
	font-size: 14px;
	line-height: 28px
}

.ui-numbertextline .ui-button:hover {
	position: relative;
	z-index: 2
}

.ui-numbertextline .ui-button:first-child {
	-webkit-border-top-right-radius: 0;
	-moz-border-radius-topright: 0;
	border-top-right-radius: 0;
	-webkit-border-bottom-right-radius: 0;
	-moz-border-radius-bottomright: 0;
	border-bottom-right-radius: 0;
	-webkit-border-bottom-left-radius: 3px;
	-moz-border-radius-bottomleft: 3px;
	border-bottom-left-radius: 3px;
	-webkit-border-top-left-radius: 3px;
	-moz-border-radius-topleft: 3px;
	border-top-left-radius: 3px
}

.ui-numbertextline .ui-button:last-child {
	-webkit-border-top-right-radius: 3px;
	-moz-border-radius-topright: 3px;
	border-top-right-radius: 3px;
	-webkit-border-bottom-right-radius: 3px;
	-moz-border-radius-bottomright: 3px;
	border-bottom-right-radius: 3px;
	-webkit-border-bottom-left-radius: 0;
	-moz-border-radius-bottomleft: 0;
	border-bottom-left-radius: 0;
	-webkit-border-top-left-radius: 0;
	-moz-border-radius-topleft: 0;
	border-top-left-radius: 0
}

.ui-numbertextline .ui-button-disabled {
	border-color: #E3E8F7;
	background: #F1F5FD;
	color: #D0DAF3
}

.ui-numbertextline .ui-button-disabled:hover {
	z-index: 0
}

.ui-numbertextline .ui-textbox {
	margin: 0 -1px;
	vertical-align: top
}

.ui-numbertextline .ui-textbox input {
	width: 100px;
	-webkit-border-radius: 0;
	-moz-border-radius: 0;
	border-radius: 0;
	text-align: center
}

.ui-numbertextline .ui-textbox input:focus {
	border-color: #b0c0e7
}

.ui-multicolumnbox table {
	margin: 0 auto;
	font-size: 12px;
	line-height: 34px
}

.ui-multicolumnbox table th {
	overflow: hidden;
	border-bottom: 1px solid #ccc;
	color: #999;
	text-align: center
}

.ui-multicolumnbox table td {
	overflow: hidden;
	border-bottom: 1px dotted #ccc;
	color: #333;
	text-align: left
}

.ui-multicolumnbox table .empty {
	width: 20px;
	border-bottom: none
}

.ui-multicolumnbox table .last {
	border-bottom: none
}

.ui-multiselect {
	overflow: hidden;
	padding: 3px 3px 3px 5px;
	padding-right: 20px;
	height: 17px;
	outline: 0;
	border: 1px solid #D8D8D8;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	border-radius: 5px;
	text-overflow: ellipsis;
	white-space: nowrap;
	word-wrap: normal;
	font-size: 12px;
	line-height: 17px;
	cursor: pointer
}

.ui-multiselect-layer {
	position: absolute;
	z-index: 1002;
	overflow-x: hidden;
	overflow-y: auto;
	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	box-sizing: border-box;
	margin: 0;
	padding: 0;
	padding: 0 1px;
	max-height: 252px;
	min-width: 100px;
	border: 1px solid #CCC;
	background: none repeat scroll 0 0 #FFF;
	-webkit-box-shadow: 0 1px 3px rgba(0,0,0,.25);
	-webkit-box-shadow: 0 1px 3px rgba(0,0,0,.25);
	-moz-box-shadow: 0 1px 3px rgba(0,0,0,.25);
	-moz-box-shadow: 0 1px 3px rgba(0,0,0,.25);
	box-shadow: 0 1px 3px rgba(0,0,0,.25);
	box-shadow: 0 1px 3px rgba(0,0,0,.25);
	list-style: none;
	text-align: left;
	font-size: 12px;
	-ms-box-sizing: border-box
}

.ui-multiselect-layer ol {
	overflow-x: hidden;
	overflow-y: auto;
	max-height: 180px
}

.ui-multiselect-layer ::-webkit-scrollbar-track {
	background-color: #E3E8F7
}

.ui-multiselect-layer ::-webkit-scrollbar-thumb {
	background-color: #999
}

.ui-multiselect-layer ::-webkit-scrollbar-button {
	background-color: #DDD
}

.ui-multiselect-layer ::-webkit-scrollbar-corner {
	background-color: #000
}

.ui-multiselect-layer ::-webkit-scrollbar {
	width: 5px
}

.ui-multiselect-head-filter {
	margin-left: 7px;
	line-height: 30px
}

.ui-multiselect-head-filter input {
	width: 95%;
	border: 1px solid #B0C0E7;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	border-radius: 5px;
	text-indent: 10px;
	line-height: 18px
}

.ui-multiselect-head-filter input:focus {
	outline: 0
}

.ui-multiselect-head,.ui-multiselect-item,.ui-multiselect-remember,.ui-multiselect-remember-filter {
	margin: 0;
	padding: 0 4px;
	color: #333;
	white-space: nowrap;
	line-height: 26px;
	cursor: pointer
}

.ui-multiselect-head .ui-multiselect-selected-box,.ui-multiselect-item .ui-multiselect-selected-box,.ui-multiselect-remember .ui-multiselect-selected-box,.ui-multiselect-remember-filter .ui-multiselect-selected-box {
	float: left;
	clear: both;
	margin-top: 8px;
	margin-right: 3px;
	padding: 0
}

.ui-multiselect-head .ui-multiselect-selected-icon,.ui-multiselect-item .ui-multiselect-selected-icon,.ui-multiselect-remember .ui-multiselect-selected-icon,.ui-multiselect-remember-filter .ui-multiselect-selected-icon {
	display: inline-block;
	width: 20px;
	height: 20px;
	vertical-align: text-top;
	line-height: 20px;
	zoom: 1
}

.ui-multiselect-head .ui-multiselect-selected-box {
	margin-top: 7px
}
```
