### ISSUE TITLE
#55 鼠标悬浮字体图标上提示信息效果

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/esay-bug-library#57]
页面代码：
``` html
<i tip="已实名认证" className="fa fa-tablet verify-pass"></i>
<i tip="手机已绑定" className="fa fa-tablet verify-pass"></i>
<i tip="邮箱已绑定" className="fa fa-tablet verify-pass"></i>
```

样式代码：
``` css
[tip] {
    position: relative
}

[tip]:after {
    width: auto;
    opacity: 0;
    z-index: 1;
    display: block;
    padding: 0 4px;
    line-height: 18px;
    position: absolute;
    visibility: hidden;
    pointer-events: none;
    color: #fff;
    font-size: 12px;
    content: attr(tip);
    background-color: rgba(18,26,44,0.8);
    top: 50%;
    left: 100%;
    white-space: pre;
    -webkit-transition: all .3s;
    transition: all .3s;
    -webkit-transform: translate(-5px, -50%);
    transform: translate(-5px, -50%);
    box-shadow: 0 0 14px rgba(0,0,0,0.1)
}

[tip]:hover {
    overflow: visible
}

[tip]:hover:after {
    opacity: .8;
    display: block;
    visibility: visible;
    -webkit-transform: translate(5px, -50%);
    transform: translate(5px, -50%)
}
```
