### ISSUE TITLE
#63 京东品类秒杀列表五栏等分布局

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/esay-bug-library#65]
> 京东品类秒杀列表五栏等分布局

- https://ms.m.jd.com/seckill/seckillList

![image](http://m.qpic.cn/psb?/V12AFk2B2E4M5B/epItMOQAJ7CNN2sduUxWTNKKoyf*kImYOnTsJ6qTBCU!/b/dDABAAAAAAAA&bo=VgW6AgAAAAADB8k!&rf=viewer_4)

说明1：消除浮动元素产生的影响，采用给父级元素添加overflow: hidden属性实现。
``` css
.tap-list {
    width: 100%;
    overflow: hidden;
}
```
