### ISSUE TITLE
#66 京东移动端首页图片列表效果

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/esay-bug-library#68]
> 京东移动端首页图片列表效果

- https://m.jd.com/

![image](http://m.qpic.cn/psb?/V12AFk2B2E4M5B/Oecy7mzwa0McD*jXVm*FNpzAMCYqcLbkdVRPLjTDpms!/b/dEYBAAAAAAAA&bo=UwW4AgAAAAADB84!&rf=viewer_4)

> 关键代码
``` css
.floor-graphic-item {
    width: 100%;
    background: #fff;
    font-size: 100%;
    overflow: hidden;
}

.graphic-col04-bg, .graphic-col04-sm {
    position: relative;
    width: 25%;
    float: left;
}

.real-show, .show-img {
    width: 100%;
    height: 100%;
    overflow: hidden;
    position: absolute;
    left: 0;
    top: 0;
}
.show-img img{
  width: 100%;
  height: 100%;
}
```
说明：基于图片实现的列表效果，注意图片的宽度和高度设置为100%，外层容器设置宽度为25%，最外层容器是通栏布局因此宽度为100%
