### ISSUE TITLE
#67 列表先导符号效果

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/esay-bug-library#69]
> 基于背景图片精灵图实现

- 页面结构代码：

``` html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>列表先导符号效果案例</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<!--新闻列表-->
	<div class="news-box">
		<ul class="news-list">
			<li class="new-item"><a class="new-link" href="#">印度企业来华干这件事 印网友感慨：壮哉我大亚洲</a></li>
			<li class="new-item"><a class="new-link" href="#">副国级海归弃外企高薪回国 年薪只相当于国外月薪</a></li>
			<li class="new-item"><a class="new-link" href="#">律师：吴小晖不服一审两罪判决 已经提起无罪上诉</a></li>
			<li class="new-item"><a class="new-link" href="#">官员有11套房自以为安全 不料这举动被大数据揪出</a></li>
		</ul>
	</div>
</body>
</html>
```

- 样式结构代码：

reset.css

``` css
/*
* @Author: mjgao@isscloud.com
* @Date:   2018-05-30 10:00:27
* @Last Modified by:   mjgao@isscloud.com
* @Last Modified time: 2018-05-30 10:00:27
*/

/* http://meyerweb.com/eric/tools/css/reset/ 
   v2.0 | 20110126
   License: none (public domain)
*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
```

main.css

``` css
/*
* @Author: mjgao@isscloud.com
* @Date:   2018-05-30 10:02:06
* @Last Modified by:   mjgao@isscloud.com
* @Last Modified time: 2018-05-30 10:02:06
*/

/**通用样式*/
a{
	color:#1f3b7b; 
	text-decoration:none;
}
a:visited{
	color:#6079b2;
}
a:hover, a:active, a:focus{
	color:#8d0000; 
	text-decoration:underline;
}

/**业务样式*/
.news-box .news-list .new-item{
	height: 20px;
	line-height: 20px;
}

.news-box .news-list .new-item .new-link{
	display: block;
	padding-left: 18px; /*使用padding-left挤出存放背景图片的位置*/
	background: url(../img/sprites.png) no-repeat -22px -220px;
}
```

- 精灵图sprites.png：

![image](http://m.qpic.cn/psb?/V12AFk2B2E4M5B/QAVCfKXpnvPIDLN4Tu*CJlrkEOJt75e9eoC5SDwrtoc!/b/dAgBAAAAAAAA&bo=KgAVAQAAAAADBxw!&rf=viewer_4)
