### ISSUE TITLE
#68 列表实现下拉菜单效果

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/esay-bug-library#70]
> 列表实现下拉菜单效果图

![image](http://m.qpic.cn/psb?/V12AFk2B2E4M5B/GoDHzCDt308zikG5SyiYw8pUDpnwo4V26jsJQiMA504!/b/dEYBAAAAAAAA&bo=EwEIAQAAAAADBzk!&rf=viewer_4)

> 基于列表和背景精灵图技术实现

- 页面结构代码：

index.html
``` html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>列表实现下拉菜单效果</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<a class="more-btn" href="javascript:;"></a>
	<div class="more-list">
		<ul>
			<li class="more-item"><a class="more-link app01" href="#">新浪财经客户端</a></li>
			<li class="more-item"><a class="more-link app02" href="#">新浪娱乐客户端</a></li>
			<li class="more-item"><a class="more-link app03" href="#">新浪体育客户端</a></li>
			<li class="more-item"><a class="more-link app04" href="#">新浪众测客户端</a></li>
			<li class="more-item last"><a class="more-link app05" href="#">新浪公开课</a></li>
		</ul>
	</div>
</body>
</html>
```

- 样式结构代码：

reset.css
``` css
/*
* @Author: mjgao@isscloud.com
* @Date:   2018-05-30 10:54:48
* @Last Modified by:   mjgao@isscloud.com
* @Last Modified time: 2018-05-30 10:54:48
*/

/* http://meyerweb.com/eric/tools/css/reset/ 
   v2.0 | 20110126
   License: none (public domain)
*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
```

main.css
``` css
/*
* @Author: mjgao@isscloud.com
* @Date:   2018-05-30 10:55:17
* @Last Modified by:   mjgao@isscloud.com
* @Last Modified time: 2018-05-30 10:55:17
*/

/**通用样式*/
body {
    background: #fff;
    color: #333;
    font: 12px/22px "宋体","Arial Narrow";
}

a{
	color:#1f3b7b; 
	text-decoration:none;
}
a:visited{
	color:#6079b2;
}
a:hover, a:active, a:focus{
	color:#8d0000; 
	text-decoration:underline;
}

/**业务样式*/
.more-btn{
	display: block;
	width: 41px;
	height: 19px;
	background: url(../img/sprites.png) no-repeat 0 -119px; /*按钮采用背景图实现*/
}

.more-list{
	 width: 135px;
	 height: 200px;
	 border: 1px solid #ccc;
	 box-shadow: 3px 3px 5px rgba(0,0,0,.6); /*边框阴影效果*/
	 background: #fff;
}

.more-list .more-item{
	margin: 0 9px;
	padding-top: 10px;
	height: 30px;
	background: url(../img/bg_line_01.png) repeat-x 0 39px; /*分割线效果采用背景图实现*/
}

.more-list .more-item.last{
	background: none;
}

.more-list .more-item .more-link{
	display: block;
	height: 20px;
	line-height: 20px;
	color: #666;
	text-indent: 28px; /*效果等同于padding-left：28px，为背景图挤出28px的空间*/
	background: url(../img/sprites.png) no-repeat 0 -20px;
}

.more-list .more-item .more-link.app01{
	background-position: 0 -20px;
}

.more-list .more-item .more-link.app02{
	background-position: 0 -40px;
}

.more-list .more-item .more-link.app03{
	background-position: 0 -60px;
}

.more-list .more-item .more-link.app04{
	background-position: 0 -243px;
}

.more-list .more-item .more-link.app05{
	background-position: 0 -80px;
}
```

- 分割线背景图：
![image](http://m.qpic.cn/psb?/V12AFk2B2E4M5B/6BC6P1LmQT3ss6fQJo2tBXazzDPOWUjCufQCdR.lg2I!/b/dFcAAAAAAAAA&bo=AgABAAAAAAADFzE!&rf=viewer_4&t=5)
