### ISSUE TITLE
#69 侧边栏固定浮层效果

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/esay-bug-library#71]
> 侧边栏固定浮层效果图

![image](http://m.qpic.cn/psb?/V12AFk2B2E4M5B/n9A1X.12uZq12o7KhEekPBIZJkXlWxBF0K7RdSw2UQ8!/b/dFUAAAAAAAAA&bo=VgV6AgAAAAADBwk!&rf=viewer_4)

> 基于背景精灵图技术实现

- 页面结构代码：

index.html
``` html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>侧边栏固定浮层效果</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<div class="page-right-bar">
		<a href="javascript:;" class="right-bar-btn btn-home">新浪首页</a>
		<a href="javascript:;" class="right-bar-btn btn-news">相关新闻</a>
		<a href="javascript:;" class="right-bar-btn btn-survey">改版调查</a>
		<a href="javascript:;" class="right-bar-btn btn-backtop">回到顶部</a>
	</div>
</body>
</html>
```

- 样式结构代码：

reset.css
``` css
/*
* @Author: mjgao@isscloud.com
* @Date:   2018-05-30 13:57:31
* @Last Modified by:   mjgao@isscloud.com
* @Last Modified time: 2018-05-30 13:57:31
*/

/* http://meyerweb.com/eric/tools/css/reset/ 
   v2.0 | 20110126
   License: none (public domain)
*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
```

main.css
``` css
/*
* @Author: mjgao@isscloud.com
* @Date:   2018-05-30 13:58:53
* @Last Modified by:   mjgao@isscloud.com
* @Last Modified time: 2018-05-30 13:58:53
*/

.page-right-bar{
	position: fixed;
	right: 0;
	top: 50%;
	width: 65px;
}

.page-right-bar .right-bar-btn{
	display: block;
	width: 65px;
	height: 65px;
	text-indent: -999em; /*隐藏文字*/
	margin-bottom: 12px;
	background: url(../img/normal-sprite-873b15.png) no-repeat;
}

.page-right-bar .right-bar-btn.btn-home{
	background-position: 0 -105px;
}

.page-right-bar .right-bar-btn.btn-home:hover{
	background-position: 0 -38px;
}

.page-right-bar .right-bar-btn.btn-news{
	background-position: -201px -105px;
}

.page-right-bar .right-bar-btn.btn-news:hover{
	background-position: -67px -172px;
}

.page-right-bar .right-bar-btn.btn-survey{
	background-position: -67px -38px;
}

.page-right-bar .right-bar-btn.btn-survey:hover{
	background-position: -201px -38px;
}

.page-right-bar .right-bar-btn.btn-backtop{
	background-position: -134px -172px;
}

.page-right-bar .right-bar-btn.btn-backtop:hover{
	background-position: -134px -105px;
}

```

- 精灵图

![image](http://m.qpic.cn/psb?/V12AFk2B2E4M5B/pV89wQLEkNxqIBdE8OuhfyMt2wm2h5*jcU8dvcMXt60!/b/dDABAAAAAAAA&bo=fALtAAAAAAADB7E!&rf=viewer_4)

> 说明
- 鼠标的悬停样式切换时通过改变背景图的位置实现的。
