### ISSUE TITLE
#70 CSS3动画实现小球闪动效果

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/esay-bug-library#72]
> 效果图

图1
![image](http://m.qpic.cn/psb?/V12AFk2B2E4M5B/ns6JyTruqK6Pobv0fR.mGdT2PgG9eQcazp6KJ0sa9nE!/b/dEMBAAAAAAAA&bo=nAL.AAAAAAADB0I!&rf=viewer_4)

图2
![image](http://m.qpic.cn/psb?/V12AFk2B2E4M5B/qi7ufdcX9V6dKYwxQLWXjPzCdhEVjr*ikRpHI1iB9xk!/b/dDEBAAAAAAAA&bo=AQLvAAAAAAADF94!&rf=viewer_4)

> 基于CSS3的animation动画技术实现

- 页面结构代码：

index.html
``` html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>小球闪动效果</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<div class="inner">
		<i class="point pulse"></i>
	</div>
</body>
</html>
```

- 样式结构代码：

reset.css
``` css
/*
* @Author: mjgao@isscloud.com
* @Date:   2018-05-30 15:02:42
* @Last Modified by:   mjgao@isscloud.com
* @Last Modified time: 2018-05-30 15:02:42
*/

/* http://meyerweb.com/eric/tools/css/reset/ 
   v2.0 | 20110126
   License: none (public domain)
*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
```

main.css
``` css
/*
* @Author: mjgao@isscloud.com
* @Date:   2018-05-30 15:03:05
* @Last Modified by:   mjgao@isscloud.com
* @Last Modified time: 2018-05-30 15:03:05
*/

.inner{
	width: 1100px;
	margin: 30px auto;
}

.point{
	display: block;
	width: 6px;
	height: 6px;
	border-radius: 50%;
	background: #ca1d18;
}

.pulse {
    animation-name: pulse;
    animation-duration: 1.2s;
    animation-iteration-count: infinite; /*规定动画应该无限次播放*/
    /* animation: name duration timing-function delay iteration-count direction; */
}

@keyframes pulse {
	0% {
		transform: scaleX(1);
		-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=30)";
		opacity: .3
	}

	50% {
		transform: scale3d(1.3,1.3,1.3);
		-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
		opacity: 1
	}

	100% {
		transform: scaleX(1);
		-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=30)";
		opacity: .3
	}
}
```

> CSS3动画语法图

![image](http://m.qpic.cn/psb?/V12AFk2B2E4M5B/lRXYl2Hw.6QWHZcd*Wlc6csvhwjLO5oJ2ixwd6rBE5I!/b/dC8BAAAAAAAA&bo=SwNjAQAAAAADFxg!&rf=viewer_4)

- http://www.w3school.com.cn/cssref/pr_animation.asp
- http://www.w3school.com.cn/cssref/pr_transform.asp
