### ISSUE TITLE
#87 webpack研究学习总结(2)

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/esay-bug-library#89]
### 案例5：基础环境搭建 支持ES6、SCSS、图片、字体

> 目录结构图

![image](http://m.qpic.cn/psb?/V12AFk2B2E4M5B/3t5A.UDfQx4eLLX56jqpDuSuyAEFzHE91botXekr6fA!/b/dC0BAAAAAAAA&bo=QAExAgAAAAADB1A!&rf=viewer_4)

- package.json

``` bash
{
  "name": "webpack-optimize",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "webpack": "node_modules/.bin/webpack --config webpack.config.js"
  },
  "author": "mjgao@isscloud.com",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.7.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^2.1.2",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.1",
    "style-loader": "^0.21.0",
    "url-loader": "^1.0.1",
    "webpack": "^2.4.1"
  },
  "dependencies": {
    "lodash": "^4.17.4"
  }
}
```

- webpack.config.js

``` js
/*
* @Author: MJ
* @Date:   2018-06-02 09:37:01
* @Last Modified by:   MJ
* @Last Modified time: 2018-06-02 13:27:50
*/
const CopyWebpackPlugin = require('copy-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');
var path = require("path");

module.exports = {
	entry: './src/demo/index.js',
	output: {
		path: path.resolve(__dirname, 'dist'),
		filename: 'js/[name]_[hash:8].js'
	},
	module: {
		rules: [
			{
				test: /\.js$/,
				use: ['babel-loader']
			},
			{
				//增加对SCSS文件的支持
				test: /\.scss$/,
				use: ExtractTextPlugin.extract({
		          fallback: 'style-loader',
		          //如果需要，可以在 sass-loader 之前将 resolve-url-loader 链接进来
		          use: ['css-loader', 'sass-loader'],
		          /*
				  * 复写css文件中资源路径
				  * webpack3.x配置在extract-text-webpack-plugin插件中
				  * 因为css文件中的外链是相对与css的，
				  * 我们抽离的css文件在可能会单独放在css文件夹内
				  * 引用其他如img/a.png会寻址错误
				  * 这种情况下所以单独需要配置../../，复写其中资源的路径
				  */
		          publicPath: '../'
		        })
			},
			{
				test: /\.(png|svg|jpg|gif)$/,
				use: [{
					loader: 'url-loader',
					options: {
						//50kb以下的文件采用url-loader
						limit: 1024 * 50,
						// 否则采用file-loader，默认值是file-loader
						fallback: 'file-loader',
						name: 'img/[name]_[hash:8].[ext]'
					}
				}]
			},
			{
                test: /\.(woff|woff2|eot|ttf|otf)$/,
                use: [
                	'file-loader'
                ]
            }
		]
	},
	plugins: [
		// 将根目录下的index.html文件拷贝到{output}配置的dist目录下
		new CopyWebpackPlugin([
			{ from: 'index.html', to: 'index.html' }
		]),
		// 每次打包前清除一下dist目录
		new CleanWebpackPlugin(
            ['dist'],　 //匹配删除的目录及文件
            {
                root: __dirname,       　　　　　　　　　　//根目录
                verbose:  true,        　　　　　　　　　　//开启在控制台输出信息
                dry:      false        　　　　　　　　　　//启用删除文件
            }
        ),
        // 提取css到单独的文件
        new ExtractTextPlugin({
        	filename: 'css/main_[contenthash:8].css'
        }),
        // 提取公共模块文件
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: function (module) {
                return module.context && module.context.indexOf('node_modules') !== -1;
            }
        }),
        //为了避免vendor.*.js的hash值发生改变需要输出一个manifest.*.js文件
        new webpack.optimize.CommonsChunkPlugin({
        	//But since there are no more common modules between them we end up with just the runtime code included in the manifest file
            name: 'manifest' 
        }),
        new HtmlWebpackPlugin({
        	filename: 'index.html',
        	template: 'index.html'
        })
	],
	// 输出 source-map 方便直接调试 ES6 源码
	devtool: 'source-map'
}
```

- .babelrc

``` bash
{
  // env项是借助插件babel-preset-env，下面这个配置说的是babel对es6,es7,es8进行转码
  "presets": [
    "env"
  ]
}
```

- index.html

``` html
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>webpack-optimize</title>
</head>
<body>
	<div class="demo_box"></div>
</body>
</html>
```

- src/demo/index.js

``` js
/*
* @Author: MJ
* @Date:   2018-06-02 11:54:44
* @Last Modified by:   MJ
* @Last Modified time: 2018-06-02 12:08:16
*/
import './index.scss';

console.log(123);
```

- src/demo/index.scss

``` css
/*
* @Author: MJ
* @Date:   2018-06-02 11:54:44
* @Last Modified by:   MJ
* @Last Modified time: 2018-06-02 13:01:58
*/
.demo_box{
	width: 500px;
	height: 300px;
	background: url(./index.jpg) no-repeat left top;
	background-size: cover;
}
```

- 编译： 执行npm run webpack后的效果图

![image](http://m.qpic.cn/psb?/V12AFk2B2E4M5B/oS0g6gOBMI9wgeb47vfd0bhS6Oja8yNlJGAFnih2DZU!/b/dAgBAAAAAAAA&bo=6AJ8AgAAAAADB7Y!&rf=viewer_4)

> 成功喽~

**Comment by Easy-MJ** [comment]
> 压缩javascript

``` js
//压缩javascript
new webpack.optimize.UglifyJsPlugin({
	//开启sourceMap
	sourceMap: true,
	uglifyOptions: {
		compress: {
			//在UglifyJs删除没有用到的代码时不输出警告
			warnings: false, 
			//删除所有console语句，可以兼容IE浏览器
			drop_console: true, 
			//内嵌已定义但是只用到一次的变量
			collapse_vars: true,
			//提取出现了多次但是没有定义成变量去引用的静态值
			reduce_vars: true
		},
		output: {
			//最紧凑的输出
			beautify: false,
			//删除所有注释
			comments: false
		}
	}
})
```

**Comment by Easy-MJ** [comment]
> 压缩css：通过minimize选项压缩css代码

``` css
{
	//增加对SCSS文件的支持
	test: /\.scss$/,
	use: ExtractTextPlugin.extract({
		fallback: 'style-loader',
		//如果需要，可以在 sass-loader 之前将 resolve-url-loader 链接进来
		//通过minimize选项压缩css代码
		use: ['css-loader?minimize', 'sass-loader'],
		/*
		* 复写css文件中资源路径
		* webpack3.x配置在extract-text-webpack-plugin插件中
		* 因为css文件中的外链是相对与css的，
		* 我们抽离的css文件在可能会单独放在css文件夹内
		* 引用其他如img/a.png会寻址错误
		* 这种情况下所以单独需要配置../../，复写其中资源的路径
		*/
		publicPath: '../'
	})
}
```
